version: '3.3'

services:
  redis01-master:
    container_name: redis-master-1
    build:
      context: .
      dockerfile: ./redis01-master/Dockerfile
    sysctls:
      net.core.somaxconn: 20000
    ulimits:
      nofile:
        soft: 64000
        hard: 64000
    ports:
      - "6379:6379"
      - "16379:16379"
    restart: 'always'
    environment:
     - REDIS_REPLICATION_MODE=master
    volumes:
      - ./redis01-master:/app/logs
      - redis-data:/var/lib/redis
      - ./redis01-master/conf/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass ${REDIS_PASS:-12345}
    networks:
      app_net:
        ipv4_address: 173.17.0.10
    depends_on:
      - redis-overcommit

  redis01-slave:
    container_name: redis-slave-1
    build:
      context: .
      dockerfile: ./redis01-slave/Dockerfile
    sysctls:
      net.core.somaxconn: 20000
    ulimits:
      nofile:
        soft: 64000
        hard: 64000
    ports:
      - "6380:6380"
      - "16380:16380"
    restart: 'always'
    environment:
     - REDIS_REPLICATION_MODE=slave
    volumes:
      - ./redis01-slave:/app/logs
      - redis-data:/var/lib/redis
      - ./redis01-slave/conf/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass ${REDIS_PASS:-12345}
    networks:
      app_net:
        ipv4_address: 173.17.0.40
    depends_on:
      - redis-overcommit
  
  redis02-master:
    container_name: redis-master-2
    build:
      context: .
      dockerfile: ./redis02-master/Dockerfile
    sysctls:
      net.core.somaxconn: 20000
    ulimits:
      nofile:
        soft: 64000
        hard: 64000
    ports:
      - "6381:6381"
      - "16381:16381"
    restart: 'always'
    environment:
     - REDIS_REPLICATION_MODE=master
    volumes:
      - ./redis02-master:/app/logs
      - redis-data:/var/lib/redis
      - ./redis02-master/conf/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass ${REDIS_PASS:-12345}
    networks:
      app_net:
        ipv4_address: 173.17.0.20
    depends_on:
      - redis-overcommit

  redis02-slave:
    container_name: redis-slave-2
    build:
      context: .
      dockerfile: ./redis02-slave/Dockerfile
    sysctls:
      net.core.somaxconn: 20000
    ulimits:
      nofile:
        soft: 64000
        hard: 64000
    ports:
      - "6382:6382"
      - "16382:16382"
    restart: 'always'
    environment:
     - REDIS_REPLICATION_MODE=slave
    volumes:
      - ./redis02-slave:/app/logs
      - redis-data:/var/lib/redis
      - ./redis02-slave/conf/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass ${REDIS_PASS:-12345}
    networks:
      app_net:
        ipv4_address: 173.17.0.50
    depends_on:
      - redis-overcommit

  redis03-master:
    container_name: redis-master-3
    build:
      context: .
      dockerfile: ./redis03-master/Dockerfile
    sysctls:
      net.core.somaxconn: 20000
    ulimits:
      nofile:
        soft: 64000
        hard: 64000
    ports:
      - "6383:6383"
      - "16383:16383"
    restart: 'always'
    environment:
     - REDIS_REPLICATION_MODE=master
    volumes:
      - ./redis03-master:/app/logs
      - redis-data:/var/lib/redis
      - ./redis03-master/conf/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass ${REDIS_PASS:-12345}
    networks:
      app_net:
        ipv4_address: 173.17.0.30
    depends_on:
      - redis-overcommit

  redis03-slave:
    container_name: redis-slave-3
    build:
      context: .
      dockerfile: ./redis03-slave/Dockerfile
    sysctls:
      net.core.somaxconn: 20000
    ulimits:
      nofile:
        soft: 64000
        hard: 64000
    ports:
      - "6384:6384"
      - "16384:16384"
    restart: 'always'
    environment:
     - REDIS_REPLICATION_MODE=slave
    volumes:
      - ./redis03-slave:/app/logs
      - redis-data:/var/lib/redis
      - ./redis03-slave/conf/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass ${REDIS_PASS:-12345}
    networks:
      app_net:
        ipv4_address: 173.17.0.60
    depends_on:
      - redis-overcommit
  
  redis-overcommit:
    build: https://github.com/bkuhl/redis-overcommit-on-host.git
    restart: 'no'
    privileged: true
    volumes:
      - /proc/sys/vm:/mnt/vm


volumes:
  redis-data:
    driver: local

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 173.17.0.0/16
          gateway: 173.17.0.1